# Project 12 -- Anthony Micco

**TA Help:** N/A
    
**Collaboration:** Used this article to assist in editing the sub class after I received errors in question 2:
https://pybit.es/articles/python-subclasses/.

## Question 1

In [1]:
# imports and data frame options
import pandas as pd 
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
#creating flight class
class Flight:

    def __init__(self,flight_number, origin_airport_ID, destination_airport_ID, departure_time, arrival_time, departure_delay, arrival_delay):

        self.flight_number = flight_number
        self.origin_airport_ID = origin_airport_ID
        self.destination_airport_ID = destination_airport_ID
        self.departure_time = departure_time
        self.arrival_time = arrival_time
        self.departure_delay = departure_delay
        self.arrival_delay = arrival_delay

        
    def getArrDelay(self):

        return self.arrival_delay
    
    def getDepDelay(self):
        return self.departure_delay
    
    
#creating ScheduledFlight subclass
class ScheduledFlight(Flight):
    
    def __init__(self, flight_number, origin_airport_ID, destination_airport_ID, departure_time, arrival_time, departure_delay, arrival_delay, CRSDepTime, CRSArrTime):
        
        super().__init__(flight_number, origin_airport_ID, destination_airport_ID, departure_time, arrival_time, departure_delay, arrival_delay)
        self.CRSDepTime = CRSDepTime
        self.CRSArrTime = CRSArrTime
    
    def isOnTime(self):
        if super().getArrDelay() <= 0 and super().getDepDelay() <= 0:
            return True
        else:
            return False

## Question 2

In [3]:
# columns to read in 
cols = [
    'DepDelay', 'ArrDelay', 'Flight_Number_Reporting_Airline', 'Distance',
    'CarrierDelay', 'WeatherDelay', 'CRSDepTime', 'CRSArrTime',
    'DepTime', 'ArrTime', 'Origin',
    'Dest', 'AirTime'
]

In [4]:
# column data types
col_types = {'DepDelay': 'float64','ArrDelay': 'float64','Flight_Number_Reporting_Airline':'int64',
             'Distance': 'float64','CarrierDelay': 'float64','WeatherDelay': 'float64', 'CRSDepTime': 'float64',
             'CRSArrTime':'float64','Dest':'object','Origin':'object','DepTime': 'float64',
             'ArrTime': 'float64','AirTime': 'float64'}

In [5]:
# creating mydf
mydf = pd.read_csv('/anvil/projects/tdm/data/flights/2014.csv', usecols=cols, dtype=col_types, nrows=100)

In [6]:
mydf.head()

,Flight_Number_Reporting_Airline,Origin,Dest,CRSDepTime,DepTime,DepDelay,CRSArrTime,ArrTime,ArrDelay,AirTime,Distance,CarrierDelay,WeatherDelay
0,2377,DFW,ICT,940.0,935.0,-5.0,1055.0,1051.0,-4.0,56.0,328.0,NaN,NaN
1,2377,DFW,ICT,940.0,951.0,11.0,1055.0,1115.0,20.0,54.0,328.0,11.0,0.0
2,2377,ICT,DFW,1135.0,1144.0,9.0,1300.0,1302.0,2.0,57.0,328.0,NaN,NaN
3,2377,ICT,DFW,1135.0,1134.0,-1.0,1300.0,1253.0,-7.0,53.0,328.0,NaN,NaN
4,2377,ICT,DFW,1135.0,1129.0,-6.0,1300.0,1244.0,-16.0,52.0,328.0,NaN,NaN

In [7]:
# initating list of flights
flightList = []

for index, row in mydf.iterrows():
    myflight = ScheduledFlight(
        flight_number = row['Flight_Number_Reporting_Airline'],
        origin_airport_ID = row['Origin'],
        destination_airport_ID = row['Dest'],
        departure_time = row['DepTime'],
        arrival_time = row['ArrTime'],
        departure_delay = row['DepDelay'],
        arrival_delay = row['ArrDelay'],
        CRSDepTime = row['CRSDepTime'],
        CRSArrTime = row['CRSArrTime']
    )

    flightList.append(myflight)

In [8]:
len(flightList)

100

## Question 3

In [9]:
# creating ontime_count dictionary
ontime_count = {}

for myflights in flightList:
    if myflights.destination_airport_ID not in ontime_count:
        ontime_count[myflights.destination_airport_ID] = []
    
    if(myflights.isOnTime()):
        ontime_count[myflights.destination_airport_ID].append(myflights.isOnTime())

In [10]:
ontime_count

{'ICT': [True],
 'DFW': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'TPA': [True, True, True, True, True, True, True, True, True, True, True],
 'OGG': [True, True, True, True, True, True, True],
 'SJC': [True, True, True],
 'KOA': [True, True, True, True],
 'SMF': [True],
 'SEA': [True, True, True, True, True, True, True],
 'PDX': [True, True, True],
 'OAK': [True, True],
 'HNL': [True, True, True, True, True, True],
 'SAN': [True, True],
 'ANC': [True, True],
 'LIH': [True, True],
 'BLI': [True],
 'DCA': [True, True]}

In [11]:
# Calculating the amount of flights on time
ontimeCount = {myairport : sum(isontime) for myairport, isontime in ontime_count.items()}

In [12]:
ontimeCount

{'ICT': 1,
 'DFW': 12,
 'TPA': 11,
 'OGG': 7,
 'SJC': 3,
 'KOA': 4,
 'SMF': 1,
 'SEA': 7,
 'PDX': 3,
 'OAK': 2,
 'HNL': 6,
 'SAN': 2,
 'ANC': 2,
 'LIH': 2,
 'BLI': 1,
 'DCA': 2}

## Question 4

In [13]:
# updated class
class ScheduledFlight(Flight):
    
    def __init__(self, flight_number, origin_airport_ID, destination_airport_ID, departure_time, arrival_time, departure_delay, arrival_delay, CRSDepTime, CRSArrTime):
        
        super().__init__(flight_number, origin_airport_ID, destination_airport_ID, departure_time, arrival_time, departure_delay, arrival_delay)
        self.CRSDepTime = CRSDepTime
        self.CRSArrTime = CRSArrTime
    
    def isOnTime(self):
        if super().getArrDelay() <= 0 and super().getDepDelay() <= 0:
            return True
        else:
            return False
        
    def isDelayed(self):
        if super().getArrDelay() > 0 and super().getDepDelay() > 0:
            return True
        else:
            return False

In [14]:
# reinitating list of flights after update
flightList = []

for index, row in mydf.iterrows():
    myflight = ScheduledFlight(
        flight_number = row['Flight_Number_Reporting_Airline'],
        origin_airport_ID = row['Origin'],
        destination_airport_ID = row['Dest'],
        departure_time = row['DepTime'],
        arrival_time = row['ArrTime'],
        departure_delay = row['DepDelay'],
        arrival_delay = row['ArrDelay'],
        CRSDepTime = row['CRSDepTime'],
        CRSArrTime = row['CRSArrTime']
    )

    flightList.append(myflight)

In [15]:
# creating delayed_count dictionary
delayed_count = {}

for myflights in flightList:
    if myflights.destination_airport_ID not in delayed_count:
        delayed_count[myflights.destination_airport_ID] = []
    
    if(myflights.isDelayed()):
        delayed_count[myflights.destination_airport_ID].append(myflights.isDelayed())

In [16]:
# Calculating the amount of flights delayed
delayedCount = {myairport : sum(isdelayed) for myairport, isdelayed in delayed_count.items()}

In [17]:
delayedCount

{'ICT': 1,
 'DFW': 13,
 'TPA': 8,
 'OGG': 0,
 'SJC': 0,
 'KOA': 0,
 'SMF': 0,
 'SEA': 0,
 'PDX': 0,
 'OAK': 0,
 'HNL': 0,
 'SAN': 0,
 'ANC': 0,
 'LIH': 0,
 'BLI': 0,
 'DCA': 0}

## Question 5

In [18]:
#df to determine what values I want to use
testdf = pd.read_csv('/anvil/projects/tdm/data/flights/2014.csv', nrows=100)

In [20]:
testdf.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,DestWac,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivAirportLandings,DivReachedDest,DivActualElapsedTime,DivArrDelay,DivDistance,Div1Airport,Div1AirportID,Div1AirportSeqID,Div1WheelsOn,Div1TotalGTime,Div1LongestGTime,Div1WheelsOff,Div1TailNum,Div2Airport,Div2AirportID,Div2AirportSeqID,Div2WheelsOn,Div2TotalGTime,Div2LongestGTime,Div2WheelsOff,Div2TailNum,Div3Airport,Div3AirportID,Div3AirportSeqID,Div3WheelsOn,Div3TotalGTime,Div3LongestGTime,Div3WheelsOff,Div3TailNum,Div4Airport,Div4AirportID,Div4AirportSeqID,Div4WheelsOn,Div4TotalGTime,Div4LongestGTime,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2014,1,1,30,4,2014-01-30,AA,19805,AA,N006AA,2377,11298,1129803,30194,DFW,"Dallas/Fort Worth, TX",TX,48,Texas,74,12278,1227802,30928,ICT,"Wichita, KS",KS,20,Kansas,62,940,935,-5.0,0.0,0.0,-1,0900-0959,17.0,952,1048,3.0,1055,1051,-4.0,0.0,0.0,-1,1000-1059,0.0,NaN,0.0,75.0,76.0,56.0,1.0,328.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,1,1,31,5,2014-01-31,AA,19805,AA,N003AA,2377,11298,1129803,30194,DFW,"Dallas/Fort Worth, TX",TX,48,Texas,74,12278,1227802,30928,ICT,"Wichita, KS",KS,20,Kansas,62,940,951,11.0,11.0,0.0,0,0900-0959,12.0,1003,1057,18.0,1055,1115,20.0,20.0,1.0,1,1000-1059,0.0,NaN,0.0,75.0,84.0,54.0,1.0,328.0,2,11.0,0.0,9.0,0.0,0.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,1,1,1,3,2014-01-01,AA,19805,AA,N002AA,2377,12278,1227802,30928,ICT,"Wichita, KS",KS,20,Kansas,62,11298,1129803,30194,DFW,"Dallas/Fort Worth, TX",TX,48,Texas,74,1135,1144,9.0,9.0,0.0,0,1100-1159,12.0,1156,1253,9.0,1300,1302,2.0,2.0,0.0,0,1300-1359,0.0,NaN,0.0,85.0,78.0,57.0,1.0,328.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,1,1,2,4,2014-01-02,AA,19805,AA,N002AA,2377,12278,1227802,30928,ICT,"Wichita, KS",KS,20,Kansas,62,11298,1129803,30194,DFW,"Dallas/Fort Worth, TX",TX,48,Texas,74,1135,1134,-1.0,0.0,0.0,-1,1100-1159,11.0,1145,1238,15.0,1300,1253,-7.0,0.0,0.0,-1,1300-1359,0.0,NaN,0.0,85.0,79.0,53.0,1.0,328.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,1,1,3,5,2014-01-03,AA,19805,AA,N014AA,2377,12278,1227802,30928,ICT,"Wichita, KS",KS,20,Kansas,62,11298,1129803,30194,DFW,"Dallas/Fort Worth, TX",TX,48,Texas,74,1135,1129,-6.0,0.0,0.0,-1,1100-1159,12.0,1141,1233,11.0,1300,1244,-16.0,0.0,0.0,-2,1300-1359,0.0,NaN,0.0,85.0,75.0,52.0,1.0,328.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
# defining my own subclass
class FlightLength(Flight):
    
    def __init__(self,flight_number, origin_airport_ID, destination_airport_ID, departure_time, arrival_time, departure_delay, arrival_delay, elasped_time):
            super().__init__(flight_number, origin_airport_ID, destination_airport_ID, departure_time, arrival_time, departure_delay, arrival_delay)
            self.elapsed_time = elasped_time
                             
    def getElapsedTime(self):
        return self.elapsed_time

In [42]:
# columns to read in
cols = [
    'DepDelay', 'ArrDelay', 'Flight_Number_Reporting_Airline', 'Distance',
    'CarrierDelay', 'WeatherDelay', 'ActualElapsedTime',
    'DepTime', 'ArrTime', 'Origin',
    'Dest', 'AirTime'
]

In [43]:
# column data types
col_types = {'DepDelay': 'float64','ArrDelay': 'float64','Flight_Number_Reporting_Airline':'int64',
             'Distance': 'float64','CarrierDelay': 'float64','WeatherDelay': 'float64',
             'ActualElapsedTime':'float64','Dest':'object','Origin':'object','DepTime': 'float64',
             'ArrTime': 'float64','AirTime': 'float64'}

In [53]:
# creating elapsed time df
elapsedDF = pd.read_csv('/anvil/projects/tdm/data/flights/2014.csv', usecols= cols, dtype=col_types, nrows=100)

In [45]:
elapsedDF.head()

,Flight_Number_Reporting_Airline,Origin,Dest,DepTime,DepDelay,ArrTime,ArrDelay,ActualElapsedTime,AirTime,Distance,CarrierDelay,WeatherDelay
0,2377,DFW,ICT,935.0,-5.0,1051.0,-4.0,76.0,56.0,328.0,NaN,NaN
1,2377,DFW,ICT,951.0,11.0,1115.0,20.0,84.0,54.0,328.0,11.0,0.0
2,2377,ICT,DFW,1144.0,9.0,1302.0,2.0,78.0,57.0,328.0,NaN,NaN
3,2377,ICT,DFW,1134.0,-1.0,1253.0,-7.0,79.0,53.0,328.0,NaN,NaN
4,2377,ICT,DFW,1129.0,-6.0,1244.0,-16.0,75.0,52.0,328.0,NaN,NaN

In [46]:
#Creating list of flights
flightList = []

for index, row in elapsedDF.iterrows():
    myflight = FlightLength(
        flight_number = row['Flight_Number_Reporting_Airline'],
        origin_airport_ID = row['Origin'],
        destination_airport_ID = row['Dest'],
        departure_time = row['DepTime'],
        arrival_time = row['ArrTime'],
        departure_delay = row['DepDelay'],
        arrival_delay = row['ArrDelay'],
        elasped_time = row['ActualElapsedTime']
    )
    
    flightList.append(myflight)

In [50]:
# Creating clapsed time count dictionary
elapsed_count = {}

for myflights in flightList:
    if myflights.destination_airport_ID not in elapsed_count:
        elapsed_count[myflights.destination_airport_ID] = []
    
    elapsed_count[myflights.destination_airport_ID].append(myflights.getElapsedTime())

In [51]:
elapsed_count

{'ICT': [76.0, 84.0],
 'DFW': [78.0,
  79.0,
  75.0,
  80.0,
  78.0,
  77.0,
  83.0,
  97.0,
  80.0,
  80.0,
  75.0,
  88.0,
  87.0,
  76.0,
  74.0,
  86.0,
  73.0,
  72.0,
  77.0,
  77.0,
  81.0,
  79.0,
  84.0,
  82.0,
  68.0,
  74.0,
  78.0,
  72.0,
  68.0,
  70.0,
  101.0],
 'TPA': [55.0,
  55.0,
  62.0,
  55.0,
  54.0,
  56.0,
  51.0,
  54.0,
  55.0,
  55.0,
  54.0,
  54.0,
  59.0,
  53.0,
  47.0,
  48.0,
  52.0,
  51.0,
  55.0,
  54.0],
 'OGG': [333.0, 330.0, 346.0, 315.0, 341.0, 345.0, 345.0, 328.0],
 'SJC': [301.0, 315.0, 320.0],
 'KOA': [314.0, 344.0, 341.0, 350.0],
 'SMF': [299.0],
 'SEA': [103.0, 352.0, 363.0, 344.0, 337.0, 329.0, 339.0, 357.0, 363.0],
 'PDX': [309.0, 327.0, 319.0],
 'OAK': [309.0, 290.0],
 'HNL': [331.0, 324.0, 354.0, 349.0, 358.0, 386.0, 367.0],
 'SAN': [342.0, 305.0, 322.0],
 'ANC': [346.0, 340.0],
 'LIH': [339.0, 331.0],
 'BLI': [339.0],
 'DCA': [262.0, 271.0]}

In [48]:
# finding the average elapsed time for each airport destination
average_elapsed_time = {myairport: sum(elapsedtime)/len(elapsedtime) for myairport,elapsedtime in elapsed_count.items()}

In [49]:
average_elapsed_time

{'ICT': 80.0,
 'DFW': 79.0,
 'TPA': 53.95,
 'OGG': 335.375,
 'SJC': 312.0,
 'KOA': 337.25,
 'SMF': 299.0,
 'SEA': 320.77777777777777,
 'PDX': 318.3333333333333,
 'OAK': 299.5,
 'HNL': 352.7142857142857,
 'SAN': 323.0,
 'ANC': 343.0,
 'LIH': 335.0,
 'BLI': 339.0,
 'DCA': 266.5}

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.